animals = ['bear', 'python', 'peacock', 'kangaroo', 'whale', 'platypus']

print animals[1]
print animals[2]
print animals[0]
print animals[3]
print animals[4]
print animals[2]
print animals[5]
print animals[4]